services:
  popup.subscriber_dictionary:
    class: modules.popup.event.dictionary.PopupEventSubscriber
    calls:
         - [ set_container, [ "@service_container" ]]
    tags:
        event.subscriber:
          - [ ]

