services:
  icon.subscriber_gui:
    class: modules.icon.event.kernel.KernelEventSubscriber
    calls:
         - [ set_container, [ "@service_container" ]]
    tags:
        event.subscriber:
          - [ ]

