services:
  terminal.subscriber_kernel:
    class: modules.terminal.event.kernel.KernelEventSubscriber
    calls:
         - [ set_container, [ "@service_container" ]]
    tags:
        event.subscriber:
          - [ ]

