services:
  indicator.subscriber_gui:
    class: modules.indicator.event.kernel.KernelEventSubscriber
    calls:
         - [ set_container, [ "@service_container" ]]
    tags:
        event.subscriber:
          - [ ]
